server:
  port: 8888
  servlet:
    context-path: /manager

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8


mybatis:
  type-aliases-package: com.lirt.manager.entity
  mapper-locations: classpath:mapper/*.xml

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      lirt:
        manager:
          mapper: debug